// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/meetings": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/projects/:projectName": {
    params: {
      "projectName": string;
    };
  };
  "/projects/:projectName/image/:imageName": {
    params: {
      "projectName": string;
      "imageName": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/meetings" | "/admin" | "/projects/:projectName" | "/projects/:projectName/image/:imageName";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/meetings.tsx": {
    id: "routes/meetings";
    page: "/meetings";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/projects.$projectName.tsx": {
    id: "routes/projects.$projectName";
    page: "/projects/:projectName";
  };
  "routes/projects.$projectName.image.$imageName.ts": {
    id: "routes/projects.$projectName.image.$imageName";
    page: "/projects/:projectName/image/:imageName";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/meetings": typeof import("./app/routes/meetings.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/projects.$projectName": typeof import("./app/routes/projects.$projectName.tsx");
  "routes/projects.$projectName.image.$imageName": typeof import("./app/routes/projects.$projectName.image.$imageName.ts");
};